select distinct
    date_estimate_sent,
    total_estimates,
    date_received,
    loss_category as customer_contact_category,
    date_closed,
    date_estimate_approved,
    date_of_loss as date_loss,
    date_invoiced,
    date_of_cos as date_cos,
    date_of_majority_completion as date_majority_completion,
    date_of_work_authorization as date_work_authorization,
    date_started,
    division,
    estimator,
    foreman,
    insurance_carrier,
    job_name,
    job_number,
    job_status as status,
    loss_address as address,
    city as city,
    state_province as state_province,
    type_of_loss,
    zip_postal_code as zip_postal_code,
    referred_by_contact as referredby_contactname,
    'Base' as source,
    branch,
    is_win as is_win,
    is_loss as is_loss,
    total_invoiced,
    date_inspected,
    total_collected
from {{ ref("base_fedex_kpi") }}
